import pygame.math

# Constantes da tela
SCREEN_SIZE = pygame.math.Vector2(640, 360)

# Constantes entity
ASTEROID_TAG = "asteroid"
BULLET_TAG = "bullet"
PLAYER_TAG = "player"
ALIEN_TAG = "alien"

# Constantes player
PLAYER_SIZE = 10
MAX_VELOCITY_OF_PLAYER = 70
MAX_LIVES = 5

# Constantes asteroid (Só valores positivos)
SMALL_ASTEROID_SIZE = 8
MEDIUM_ASTEROID_SIZE = 16
BIG_ASTEROID_SIZE = 32

CORRECTION_CONSTANT = 800
SMALL_ASTEROID_VELOCITY = CORRECTION_CONSTANT / SMALL_ASTEROID_SIZE
MEDIUM_ASTEROID_VELOCITY = CORRECTION_CONSTANT / MEDIUM_ASTEROID_SIZE
BIG_ASTEROID_VELOCITY = CORRECTION_CONSTANT / BIG_ASTEROID_SIZE

# Constantes bullet
BULLET_SIZE = 2
VELOCITY_OF_BULLET = 80
BULLET_LIFE_TIME = 10

# Constantes weapon
WEAPON_COOLDOWN = 1
MAX_AMMUNITION = 1000


